In [204]:
import numpy as np
import sympy
from sympy import lambdify
np.set_printoptions(suppress=True)

* y
* y = 2x + 1
* y = -2x + 10
* y = 3x + 1
* y = -3x + 15

In [205]:
x = np.array([[1, 2, 3, 4, 5], [3, 5, 7, 9, 11], [8, 6, 4, 2, 0], [4, 7, 10, 13, 16], [12, 9, 6, 3, 0]])
# x = np.array([[3, 5, 7, 9, 11], [8, 6, 4, 2, 0], [1, 2, 3, 4, 5], [4, 7, 10, 13, 16], [12, 9, 6, 3, 0]])

# x = np.array(
#     [
#         [ 8.27159,     4.68336895,  9.13376062, 14.95777334, 10.27004708],
#         [ 4.68336895,  0.7610481,   2.53578632, 14.58413486,  8.93209007],
#         [ 9.13376062,  2.53578632, 10.12321066, 13.32925066,  5.20644467],
#         [14.95777334, 14.58413486, 13.32925066, 10.65992706, 14.62357189],
#         [10.27004708,  8.93209007,  5.20644467, 14.62357189, 17.42619585]
#     ]
# )

# x = np.array(
#     [
#         [ 0.827159,     0.468336895,  0.913376062, 0.1495777334, 0.1027004708],
#         [ 0.468336895,  0.07610481,   0.253578632, 0.1458413486,  0.893209007],
#         [ 0.913376062,  0.253578632, 0.1012321066, 0.1332925066,  0.520644467],
#         [0.1495777334, 0.1458413486, 0.1332925066, 0.1065992706, 0.1462357189],
#         [0.1027004708,  0.893209007,  0.520644467, 0.1462357189, 0.1742619585]
#     ]
# )

In [206]:
# # x = o/e matrix 
# # Create a nxn array with random positive values
# x = np.random.rand(5, 5) * 10

# # Make the array symmetric
# x = x + x.T

# # Ensure all values are positive
# x[x < 0] = np.random.rand() * 10

# # Print the array
# display(x)

In [207]:
### Zero mean
for i in range(len(x)):
    x[i] = x[i] - np.mean(x[i])
x

array([[-2, -1,  0,  1,  2],
       [-4, -2,  0,  2,  4],
       [ 4,  2,  0, -2, -4],
       [-6, -3,  0,  3,  6],
       [ 6,  3,  0, -3, -6]])

In [208]:
corr_x = np.corrcoef(x)
display(corr_x)

array([[ 1.,  1., -1.,  1., -1.],
       [ 1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1.]])

In [209]:
x1 = x[0]
pred_x = np.array([x1])
mean_x1 = np.mean(x1)
std_x1 = np.std(x1)

for index, xj in enumerate(x):
    xj = np.array([xj])
    mean_xj = np.mean(xj)
    std_xj = np.std(xj)
    
    r = corr_x[index][0]
    # print(r)
    
    ### pred_xj = r * (std_xj / std_x1) * (x1 - mean_x1) + mean_xj
    ### y = a * x + b
    a = r * (std_xj / std_x1)
    b = -(r * (std_xj / std_x1) * mean_x1) + mean_xj
    pred_xj = a * x1 + b
    # print(a)
    # print(f'{b:.20f}\n')

    pred_xj = np.array([pred_xj])

    if index != 0:
        pred_x = np.concatenate((pred_x, pred_xj), axis=0)


In [210]:
display(corr_x)

array([[ 1.,  1., -1.,  1., -1.],
       [ 1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1.]])

### PCA

In [211]:
arr = [x]
EV1 = []

for target_x in arr:
    n = len(target_x[0])

    x_t = np.transpose(target_x)
    y = x_t / np.sqrt(n)

    U, S, Vh = np.linalg.svd(y, full_matrices=True)
    eigenvalues = S * S
    sum_eigenvalues = np.sum(eigenvalues)
    explained_variances = eigenvalues / sum_eigenvalues
    display(eigenvalues)
    display(explained_variances)
    display(np.sum(explained_variances))

    cov_x = np.matmul(np.transpose(y), y)
    V_Cx = np.matmul(Vh, cov_x)
    
    # print(np.matmul(V_Cx, np.transpose(Vh)))
    # print(f'{np.matmul(V_Cx[0], Vh[1]):.20f}\n')
    # print(f'{np.matmul(Vh[0], Vh[0]):.20f}\n')

    ## Confirm that XV = US
    # display(np.matmul(y, np.transpose(Vh))) 
    # display(np.matmul(U, np.diag(S)))

    ## Confirm that the mean of project vector y equals to zero.
    # project_y = np.matmul(Vh[0], target_x)
    # display(project_y)
    # display(np.mean(project_y))
    
    ## EV1
    EV1 = (Vh[0])

    # display(np.round(cov_x, 6))
    # print(np.dot(Vh[-1], cov_x[0]))
    # print(np.dot(Vh[-1], cov_x[1]))
    # print(np.dot(Vh[-1], cov_x[2]))
    # print(np.dot(Vh[-1], cov_x[3]))
    # print(np.dot(Vh[-1], cov_x[4]))

    cov_x_GaussForm = []
    add_col = []
    for i in range(len(cov_x[0])):
        add_col.append([np.dot(Vh[-1], cov_x[i])])

    add_col = np.array(add_col)

    cov_x_GaussForm = np.concatenate((cov_x, add_col), axis=1)
    cov_x_rref = sympy.Matrix(cov_x_GaussForm).rref()
    Base_Vec = []

    # print(np.round(cov_x_GaussForm, 4))
    # display(cov_x_rref[0])

    for i in cov_x_rref[0]:
        if i != 0 and i != 1:
            Base_Vec.append(i)
    
    # print(Vh[-1] / Base_Vec)
    # print('\n')
    
    # print(Base_Vec)
    # print(Vh[-1])
    # print(EV1)
    # print('\n')
    
    # print(cov_x)
    # print('\n')

    # print(np.dot(EV1, Base_Vec))
    # print(np.dot(EV1, Vh[-1]))

    # display(corr_x > 0)
    # display(Vh > 0)
    # display(V_Cx > 0)
    # display((Vh > 0) == (V_Cx > 0))
            
    display(EV1)
    display(target_x)
    display(cov_x)
    display(np.corrcoef(target_x))

array([54.,  0.,  0.,  0.,  0.])

array([1., 0., 0., 0., 0.])

1.0

array([ 0.19245009,  0.38490018, -0.38490018,  0.57735027, -0.57735027])

array([[-2, -1,  0,  1,  2],
       [-4, -2,  0,  2,  4],
       [ 4,  2,  0, -2, -4],
       [-6, -3,  0,  3,  6],
       [ 6,  3,  0, -3, -6]])

array([[  2.,   4.,  -4.,   6.,  -6.],
       [  4.,   8.,  -8.,  12., -12.],
       [ -4.,  -8.,   8., -12.,  12.],
       [  6.,  12., -12.,  18., -18.],
       [ -6., -12.,  12., -18.,  18.]])

array([[ 1.,  1., -1.,  1., -1.],
       [ 1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1.]])

In [212]:
# import sympy
## row echelon form
# sympy.Matrix([[1, 0, 2, 4, -8],[0, 1, -3, -1, 6], [-3, -1, -3, 1, -6], [-1, 1, -5, -2, 8]]).rref()

#### New idea: Predict EV1 matrix

In [213]:
# EV1_Vote_Matrix = corr_x > 0
# EV1_Pred_Result = []

# EV1_Vote_Matrix = np.dstack((x, EV1_Vote_Matrix))

# for row in EV1_Vote_Matrix:
#     # display(row)
#     pos_abs_sum = 0
#     neg_abs_sum = 0

#     for entry in row:
#         if entry[1]:
#             pos_abs_sum += abs(entry[0])
#         else:
#             neg_abs_sum += abs(entry[0])

#     if pos_abs_sum >= neg_abs_sum:
#         EV1_Pred_Result.append(True)
#     else:
#         EV1_Pred_Result.append(False)

#     pos_abs_sum = 0
#     neg_abs_sum = 0


# # display(list(corr_x[0] > 0))
# display(list(EV1 > 0))
# display(EV1_Pred_Result)

In [214]:
# display()

y = a * x1 + Error.<br>
a * x1 can be either positive or negative.

In [215]:
# error_x = x - pred_x
# display(x)
# display(pred_x)
# display(error_x)
# display(corr_x)

In [216]:
# pred_EV1 = []
# n = len(pred_x[0])
# counter = 0

# for i in range(n):
#     for j in range(n):
#         Leader = pred_x[i][j] if abs(pred_x[i][j]) > abs(error_x[i][j]) else error_x[i][j]
#         if Leader > 0:
#             counter += 1
    
#     print(counter)
#     if counter > n/2:
#         pred_EV1.append(True)
#     else:
#         pred_EV1.append(False)
        
#     counter = 0

# display(pred_EV1)