In [718]:
import numpy as np
np.set_printoptions(suppress=True)

* y
* y = 2x + 1
* y = -2x + 10
* y = 3x + 1
* y = -3x + 15

In [719]:
# x = np.array([[1, 2, 3, 4, 5], [3, 5, 7, 9, 11], [8, 6, 4, 2, 0], [4, 7, 10, 13, 16], [12, 9, 6, 3, 0]])

# x = np.array(
#     [
#         [ 8.27159,     4.68336895,  9.13376062, 14.95777334, 10.27004708],
#         [ 4.68336895,  0.7610481,   2.53578632, 14.58413486,  8.93209007],
#         [ 9.13376062,  2.53578632, 10.12321066, 13.32925066,  5.20644467],
#         [14.95777334, 14.58413486, 13.32925066, 10.65992706, 14.62357189],
#         [10.27004708,  8.93209007,  5.20644467, 14.62357189, 17.42619585]
#     ]
# )

x = np.array(
    [
        [ 0.827159,     0.468336895,  0.913376062, 0.1495777334, 0.1027004708],
        [ 0.468336895,  0.07610481,   0.253578632, 0.1458413486,  0.893209007],
        [ 0.913376062,  0.253578632, 0.1012321066, 0.1332925066,  0.520644467],
        [0.1495777334, 0.1458413486, 0.1332925066, 0.1065992706, 0.1462357189],
        [0.1027004708,  0.893209007,  0.520644467, 0.1462357189, 0.1742619585]
    ]
)

In [720]:
### Zero mean
for i in range(len(x)):
    x[i] = x[i] - np.mean(x[i])

In [721]:
corr_x = np.corrcoef(x)
display(corr_x)

array([[ 1.        , -0.2763315 ,  0.18560768,  0.34919255,  0.22634797],
       [-0.2763315 ,  1.        ,  0.56283175,  0.45864124, -0.56183412],
       [ 0.18560768,  0.56283175,  1.        ,  0.64287411, -0.48740165],
       [ 0.34919255,  0.45864124,  0.64287411,  1.        ,  0.23762924],
       [ 0.22634797, -0.56183412, -0.48740165,  0.23762924,  1.        ]])

In [722]:
x1 = x[0]
pred_x = np.array([x1])
mean_x1 = np.mean(x1)
std_x1 = np.std(x1)

for index, xj in enumerate(x):
    xj = np.array([xj])
    mean_xj = np.mean(xj)
    std_xj = np.std(xj)
    
    r = corr_x[index][0]
    print(r)
    
    ### pred_xj = r * (std_xj / std_x1) * (x1 - mean_x1) + mean_xj
    ### y = a * x + b
    a = r * (std_xj / std_x1)
    b = -(r * (std_xj / std_x1) * mean_x1) + mean_xj
    pred_xj = a * x1 + b
    # print(a)
    # print(f'{b:.20f}')

    pred_xj = np.array([pred_xj])

    if index != 0:
        pred_x = np.concatenate((pred_x, pred_xj), axis=0)

1.0
-0.2763315024998684
0.1856076800244789
0.3491925462421577
0.22634797329306186


In [723]:
corr_pred_x = np.corrcoef(pred_x)

display(corr_x)
display(np.round(corr_pred_x, 8))

array([[ 1.        , -0.2763315 ,  0.18560768,  0.34919255,  0.22634797],
       [-0.2763315 ,  1.        ,  0.56283175,  0.45864124, -0.56183412],
       [ 0.18560768,  0.56283175,  1.        ,  0.64287411, -0.48740165],
       [ 0.34919255,  0.45864124,  0.64287411,  1.        ,  0.23762924],
       [ 0.22634797, -0.56183412, -0.48740165,  0.23762924,  1.        ]])

array([[ 1., -1.,  1.,  1.,  1.],
       [-1.,  1., -1., -1., -1.],
       [ 1., -1.,  1.,  1.,  1.],
       [ 1., -1.,  1.,  1.,  1.],
       [ 1., -1.,  1.,  1.,  1.]])

In [724]:
display(np.round(x, 8))
display(np.round(pred_x, 8))

array([[ 0.33492897, -0.02389314,  0.42114603, -0.3426523 , -0.38952956],
       [ 0.10092276, -0.29130933, -0.11383551, -0.22157279,  0.52579487],
       [ 0.52895131, -0.13084612, -0.28319265, -0.25113225,  0.13621971],
       [ 0.01326842,  0.00953203, -0.00301681, -0.02971005,  0.0099264 ],
       [-0.26470985,  0.52579868,  0.15323414, -0.22117461, -0.19314837]])

array([[ 0.33492897, -0.02389314,  0.42114603, -0.3426523 , -0.38952956],
       [-0.08148961,  0.0058133 , -0.10246658,  0.08336873,  0.09477416],
       [ 0.05630183, -0.00401646,  0.07079499, -0.05760013, -0.06548024],
       [ 0.00554524, -0.00039559,  0.00697268, -0.00567311, -0.00644923],
       [ 0.06847326, -0.00488474,  0.08609957, -0.07005222, -0.07963586]])

### PCA

In [725]:
arr = [x, pred_x]

for target_x in arr:
    n = len(target_x[0])
    x_t = np.transpose(target_x)
    y = x_t / np.sqrt(n)

    U, S, Vh = np.linalg.svd(y, full_matrices=True)
    eigenvalues = S * S
    sum_eigenvalues = np.sum(eigenvalues)
    explained_variances = eigenvalues / sum_eigenvalues

    # display(explained_variances)
    # display(np.sum(explained_variances))
    
    ## Confirm that XV = US
    # display(np.matmul(y, np.transpose(Vh))) 
    # display(np.matmul(U, np.diag(S)))
    
    ## EV1
    display(Vh[0])

array([-0.24737165,  0.58691885,  0.50979519,  0.00898713, -0.57824012])

array([-0.94091861,  0.2289294 , -0.15816919, -0.01557827, -0.19236246])

In [726]:
display(corr_x)
display(corr_pred_x)

array([[ 1.        , -0.2763315 ,  0.18560768,  0.34919255,  0.22634797],
       [-0.2763315 ,  1.        ,  0.56283175,  0.45864124, -0.56183412],
       [ 0.18560768,  0.56283175,  1.        ,  0.64287411, -0.48740165],
       [ 0.34919255,  0.45864124,  0.64287411,  1.        ,  0.23762924],
       [ 0.22634797, -0.56183412, -0.48740165,  0.23762924,  1.        ]])

array([[ 1., -1.,  1.,  1.,  1.],
       [-1.,  1., -1., -1., -1.],
       [ 1., -1.,  1.,  1.,  1.],
       [ 1., -1.,  1.,  1.,  1.],
       [ 1., -1.,  1.,  1.,  1.]])