In [479]:
import numpy as np
np.set_printoptions(suppress=True)

* y
* y = 2x + 1
* y = -2x + 10
* y = 3x + 1
* y = -3x + 15

In [480]:
# x = np.array([[1, 2, 3, 4, 5], [3, 5, 7, 9, 11], [8, 6, 4, 2, 0], [4, 7, 10, 13, 16], [12, 9, 6, 3, 0]])

# x = np.array(
#     [
#         [ 8.27159,     4.68336895,  9.13376062, 14.95777334, 10.27004708],
#         [ 4.68336895,  0.7610481,   2.53578632, 14.58413486,  8.93209007],
#         [ 9.13376062,  2.53578632, 10.12321066, 13.32925066,  5.20644467],
#         [14.95777334, 14.58413486, 13.32925066, 10.65992706, 14.62357189],
#         [10.27004708,  8.93209007,  5.20644467, 14.62357189, 17.42619585]
#     ]
# )

# x = np.array(
#     [
#         [ 0.827159,     0.468336895,  0.913376062, 0.1495777334, 0.1027004708],
#         [ 0.468336895,  0.07610481,   0.253578632, 0.1458413486,  0.893209007],
#         [ 0.913376062,  0.253578632, 0.1012321066, 0.1332925066,  0.520644467],
#         [0.1495777334, 0.1458413486, 0.1332925066, 0.1065992706, 0.1462357189],
#         [0.1027004708,  0.893209007,  0.520644467, 0.1462357189, 0.1742619585]
#     ]
# )

In [481]:
# x = o/e matrix 
# Create a nxn array with random positive values
x = np.random.rand(3, 3) * 10

# Make the array symmetric
x = x + x.T

# Ensure all values are positive
x[x < 0] = np.random.rand() * 10

# Print the array
display(x)

array([[ 8.51282747,  4.43074988, 14.99500328],
       [ 4.43074988, 13.85127769, 12.43470134],
       [14.99500328, 12.43470134, 16.6955006 ]])

In [482]:
### Zero mean
for i in range(len(x)):
    x[i] = x[i] - np.mean(x[i])
x

array([[-0.80003274, -4.88211033,  5.68214307],
       [-5.80815975,  3.61236805,  2.1957917 ],
       [ 0.28660154, -2.2737004 ,  1.98709886]])

In [483]:
corr_x = np.corrcoef(x)
display(corr_x)

array([[ 1.        , -0.00946854,  0.96979509],
       [-0.00946854,  1.        , -0.25309266],
       [ 0.96979509, -0.25309266,  1.        ]])

In [484]:
x1 = x[0]
pred_x = np.array([x1])
mean_x1 = np.mean(x1)
std_x1 = np.std(x1)

for index, xj in enumerate(x):
    xj = np.array([xj])
    mean_xj = np.mean(xj)
    std_xj = np.std(xj)
    
    r = corr_x[index][0]
    # print(r)
    
    ### pred_xj = r * (std_xj / std_x1) * (x1 - mean_x1) + mean_xj
    ### y = a * x + b
    a = r * (std_xj / std_x1)
    b = -(r * (std_xj / std_x1) * mean_x1) + mean_xj
    pred_xj = a * x1 + b
    print(a)
    print(f'{b:.20f}\n')

    pred_xj = np.array([pred_xj])

    if index != 0:
        pred_x = np.concatenate((pred_x, pred_xj), axis=0)


1.0
0.00000000000000000000

-0.009028233686219632
0.00000000000000029873

0.39044118147996554
0.00000000000000106864



In [485]:
corr_pred_x = np.corrcoef(pred_x)

display(corr_x)
display(np.round(corr_pred_x, 8))

array([[ 1.        , -0.00946854,  0.96979509],
       [-0.00946854,  1.        , -0.25309266],
       [ 0.96979509, -0.25309266,  1.        ]])

array([[ 1., -1.,  1.],
       [-1.,  1., -1.],
       [ 1., -1.,  1.]])

In [486]:
display(np.round(x, 8))
display(np.round(pred_x, 8))

array([[-0.80003274, -4.88211033,  5.68214307],
       [-5.80815975,  3.61236805,  2.1957917 ],
       [ 0.28660154, -2.2737004 ,  1.98709886]])

array([[-0.80003274, -4.88211033,  5.68214307],
       [ 0.00722288,  0.04407683, -0.05129972],
       [-0.31236573, -1.90617692,  2.21854265]])

### PCA

In [487]:
arr = [x]
EV1 = []

for target_x in arr:
    n = len(target_x[0])

    x_t = np.transpose(target_x)
    y = x_t / np.sqrt(n)

    U, S, Vh = np.linalg.svd(y, full_matrices=True)
    eigenvalues = S * S
    sum_eigenvalues = np.sum(eigenvalues)
    explained_variances = eigenvalues / sum_eigenvalues
    display(eigenvalues)
    display(explained_variances)
    display(np.sum(explained_variances))

    cov_x = np.matmul(np.transpose(y), y)
    V_Cx = np.matmul(Vh, cov_x)
    
    # print(np.matmul(V_Cx, np.transpose(Vh)))
    # print(f'{np.matmul(V_Cx[0], Vh[1]):.20f}\n')
    # print(f'{np.matmul(Vh[0], Vh[0]):.20f}\n')

    ## Confirm that XV = US
    # display(np.matmul(y, np.transpose(Vh))) 
    # display(np.matmul(U, np.diag(S)))

    ## Confirm that the mean of project vector y equals to zero.
    # project_y = np.matmul(Vh[0], target_x)
    # display(project_y)
    # display(np.mean(project_y))
    
    ## EV1
    EV1 = (Vh[0])
    # display(Vh[0])
    
    # display(np.round(V_Cx, 6))
    # display(np.round(Vh, 6))
    # display(np.round(cov_x, 6))

    display(corr_x > 0)
    display(Vh > 0)
    display(V_Cx > 0)
    display((Vh > 0) == (V_Cx > 0))

array([21.97820146, 17.21101291,  0.        ])

array([0.56082271, 0.43917729, 0.        ])

1.0

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

array([[ True, False,  True],
       [False, False,  True],
       [False,  True,  True]])

array([[ True, False,  True],
       [False, False,  True],
       [False, False,  True]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

#### New idea: Predict EV1 matrix

In [488]:
# EV1_Vote_Matrix = corr_x > 0
# EV1_Pred_Result = []

# EV1_Vote_Matrix = np.dstack((x, EV1_Vote_Matrix))

# for row in EV1_Vote_Matrix:
#     # display(row)
#     pos_abs_sum = 0
#     neg_abs_sum = 0

#     for entry in row:
#         if entry[1]:
#             pos_abs_sum += abs(entry[0])
#         else:
#             neg_abs_sum += abs(entry[0])

#     if pos_abs_sum >= neg_abs_sum:
#         EV1_Pred_Result.append(True)
#     else:
#         EV1_Pred_Result.append(False)

#     pos_abs_sum = 0
#     neg_abs_sum = 0


# # display(list(corr_x[0] > 0))
# display(list(EV1 > 0))
# display(EV1_Pred_Result)

y = a * x1 + Error.<br>
a * x1 can be either positive or negative.

In [489]:
# error_x = x - pred_x
# display(x)
# display(pred_x)
# display(error_x)
# display(corr_x)

In [490]:
# pred_EV1 = []
# n = len(pred_x[0])
# counter = 0

# for i in range(n):
#     for j in range(n):
#         Leader = pred_x[i][j] if abs(pred_x[i][j]) > abs(error_x[i][j]) else error_x[i][j]
#         if Leader > 0:
#             counter += 1
    
#     print(counter)
#     if counter > n/2:
#         pred_EV1.append(True)
#     else:
#         pred_EV1.append(False)
        
#     counter = 0

# display(pred_EV1)