In [37]:
import numpy as np
import sympy
from sympy import lambdify
np.set_printoptions(suppress=True)
np.set_printoptions(precision=4)

* y
* y = 2x + 1
* y = -2x + 10
* y = 3x + 1
* y = -3x + 15

In [38]:
# x = np.array([[1, 2, 3, 4, 5], [3, 5, 7, 9, 11], [8, 6, 4, 2, 0], [4, 7, 10, 13, 16], [12, 9, 6, 3, 0]])

In [39]:
def generate_matrix_with_dominant_pc(variance_threshold_L = 0.8, variance_threshold_U = 1):
    """Generates a random 5x5 symmetric matrix with positive values and
       the first PC explaining at least 90% of the variance.
    """

    while True:
        # Create a nxn array with random positive values
        matrix = np.abs(np.random.randn(6, 6) * 10)  # Use absolute values for positive entries
        # Make the array symmetric
        matrix = matrix + matrix.T
        
        origin_matrix = matrix
        # Subtract the mean of each row to center the data
        matrix = matrix - matrix.mean(axis=1, keepdims=True)

        # SVD 
        n = len(matrix[0])
        matrix_t = np.transpose(matrix)
        y = matrix_t / np.sqrt(n)
        U, S, Vh = np.linalg.svd(y, full_matrices=True)
        eigenvalues = S * S
        EV1_explained_variance = eigenvalues[0] / np.sum(eigenvalues) 


        # Check if the first PC explains at least the desired variance
        if EV1_explained_variance >= variance_threshold_L and EV1_explained_variance < variance_threshold_U:
            print(EV1_explained_variance, '\n')
            print(origin_matrix, '\n')
            print(matrix, '\n')
            return matrix

# Generate a matrix that meets the conditions
x = generate_matrix_with_dominant_pc()

0.8209841388444634 

[[ 6.6669 15.6096 20.4649  9.6963 13.7713 17.3201]
 [15.6096 13.9081 14.6768 27.0354  6.305  11.0884]
 [20.4649 14.6768  5.1669 13.1834 16.8841 18.8028]
 [ 9.6963 27.0354 13.1834  7.4831 12.2795 15.6994]
 [13.7713  6.305  16.8841 12.2795 25.7657 25.4212]
 [17.3201 11.0884 18.8028 15.6994 25.4212 82.2886]] 

[[ -7.2546   1.6881   6.5434  -4.2252  -0.1502   3.3986]
 [  0.8391  -0.8625  -0.0937  12.2649  -8.4656  -3.6821]
 [  5.6018  -0.1863  -9.6963  -1.6797   2.0209   3.9396]
 [ -4.5333  12.8059  -1.0461  -6.7464  -1.95     1.4698]
 [ -2.9665 -10.4328   0.1463  -4.4583   9.0279   8.6834]
 [-11.1167 -17.3483  -9.6339 -12.7374  -3.0156  53.8518]] 



### PCA

In [40]:
n = len([0])
x_t = np.transpose(x)
y = x_t / np.sqrt(n)

U, S, Vh = np.linalg.svd(y, full_matrices=True)
eigenvalues = S * S
sum_eigenvalues = np.sum(eigenvalues)
explained_variances = eigenvalues / sum_eigenvalues
print(np.round(explained_variances, 4), '\n')

cov_x = np.matmul(np.transpose(y), y)
V_Cx = np.matmul(Vh, cov_x)

print(Vh[0], '\n')
print(cov_x, '\n')

cov_x_sum = [np.sum(np.abs(row)) for row in cov_x]
print(cov_x_sum, '\n') 

print((cov_x > 0) == (np.corrcoef(x) > 0))

[0.821  0.0762 0.0573 0.0439 0.0016 0.    ] 

[ 0.0627 -0.0988  0.0717  0.0009  0.2023  0.9697] 

[[ 127.7211  -71.2205  -84.217    81.4533   51.8585  225.6133]
 [ -71.2205  237.1077  -46.4464  -86.3983 -156.5845 -322.4439]
 [ -84.217   -46.4464  147.8585   -4.4554   43.8508  261.8314]
 [  81.4533  -86.3983   -4.4554  237.1118  -95.0709    9.2776]
 [  51.8585 -156.5845   43.8508  -95.0709  294.4463  709.7379]
 [ 225.6133 -322.4439  261.8314    9.2776  709.7379 3588.7083]] 

[642.0836839365845, 920.2013089855163, 588.6594407989783, 513.7671724332733, 1351.5488462696212, 5117.612456826116] 

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


Test-V3: Confirm the reltionship between the EV1's pos-neg pattern and the corresponding Covariance matrix row.

If the explained variance is high enough, the EV1's pos-neg pattern will match the pos-neg pattern of the Covariance matrix with maximal absolute value sum of that row (compare to every row of the covariance matirx)


According to POSSUMM, the PCA is performed on the Hi-C contact matrix with nonzero entries, not the Pearson correlation matrix (MOSAIC perform on corrected O/E matrix)