In [415]:
import numpy as np
import sympy
from sympy import lambdify
np.set_printoptions(suppress=True)

* y
* y = 2x + 1
* y = -2x + 10
* y = 3x + 1
* y = -3x + 15

In [416]:
# x = np.array([[1, 2, 3, 4, 5], [3, 5, 7, 9, 11], [8, 6, 4, 2, 0], [4, 7, 10, 13, 16], [12, 9, 6, 3, 0]])

# x = np.array(
#     [
#         [ 8.27159,     4.68336895,  9.13376062, 14.95777334, 10.27004708],
#         [ 4.68336895,  0.7610481,   2.53578632, 14.58413486,  8.93209007],
#         [ 9.13376062,  2.53578632, 10.12321066, 13.32925066,  5.20644467],
#         [14.95777334, 14.58413486, 13.32925066, 10.65992706, 14.62357189],
#         [10.27004708,  8.93209007,  5.20644467, 14.62357189, 17.42619585]
#     ]
# )

# x = np.array(
#     [
#         [ 0.827159,     0.468336895,  0.913376062, 0.1495777334, 0.1027004708],
#         [ 0.468336895,  0.07610481,   0.253578632, 0.1458413486,  0.893209007],
#         [ 0.913376062,  0.253578632, 0.1012321066, 0.1332925066,  0.520644467],
#         [0.1495777334, 0.1458413486, 0.1332925066, 0.1065992706, 0.1462357189],
#         [0.1027004708,  0.893209007,  0.520644467, 0.1462357189, 0.1742619585]
#     ]
# )

In [417]:
# x = o/e matrix 
# Create a nxn array with random positive values
x = np.random.rand(5, 5) * 10

# Make the array symmetric
x = x + x.T

# Ensure all values are positive
x[x < 0] = np.random.rand() * 10

# Print the array
display(x)

array([[ 1.3442322 ,  8.92604679, 10.03644935, 12.39513998,  8.63651788],
       [ 8.92604679,  8.34674989, 10.54291084, 16.99944417,  4.01816922],
       [10.03644935, 10.54291084, 19.28281392, 11.84014122, 12.81038423],
       [12.39513998, 16.99944417, 11.84014122, 14.94492131,  9.14944645],
       [ 8.63651788,  4.01816922, 12.81038423,  9.14944645,  3.69615037]])

In [418]:
### Zero mean
for i in range(len(x)):
    x[i] = x[i] - np.mean(x[i])
x

array([[-6.92344504,  0.65836955,  1.76877211,  4.12746274,  0.36884064],
       [-0.84061739, -1.4199143 ,  0.77624666,  7.23277999, -5.74849496],
       [-2.86609056, -2.35962907,  6.38027401, -1.0623987 , -0.09215568],
       [-0.67067865,  3.93362554, -1.22567741,  1.87910269, -3.91637218],
       [ 0.97438425, -3.64396441,  5.1482506 ,  1.48731282, -3.96598326]])

In [419]:
corr_x = np.corrcoef(x)
display(corr_x)

array([[ 1.        ,  0.43557538,  0.40702309,  0.22788542,  0.07305188],
       [ 0.43557538,  1.        ,  0.05065822,  0.53109969,  0.58095927],
       [ 0.40702309,  0.05065822,  1.        , -0.37423035,  0.65531674],
       [ 0.22788542,  0.53109969, -0.37423035,  1.        , -0.06437078],
       [ 0.07305188,  0.58095927,  0.65531674, -0.06437078,  1.        ]])

In [420]:
x1 = x[0]
pred_x = np.array([x1])
mean_x1 = np.mean(x1)
std_x1 = np.std(x1)

for index, xj in enumerate(x):
    xj = np.array([xj])
    mean_xj = np.mean(xj)
    std_xj = np.std(xj)
    
    r = corr_x[index][0]
    # print(r)
    
    ### pred_xj = r * (std_xj / std_x1) * (x1 - mean_x1) + mean_xj
    ### y = a * x + b
    a = r * (std_xj / std_x1)
    b = -(r * (std_xj / std_x1) * mean_x1) + mean_xj
    pred_xj = a * x1 + b
    print(a)
    print(f'{b:.20f}\n')

    pred_xj = np.array([pred_xj])

    if index != 0:
        pred_x = np.concatenate((pred_x, pred_xj), axis=0)


1.0
0.00000000000000000000

0.49500277989068747
-0.00000000000000000710

0.36634136756501307
0.00000000000000123115

0.1656759545720591
-0.00000000000000011983

0.0675266141505299
-0.00000000000000043695



In [421]:
corr_pred_x = np.corrcoef(pred_x)

display(corr_x)
display(np.round(corr_pred_x, 8))

array([[ 1.        ,  0.43557538,  0.40702309,  0.22788542,  0.07305188],
       [ 0.43557538,  1.        ,  0.05065822,  0.53109969,  0.58095927],
       [ 0.40702309,  0.05065822,  1.        , -0.37423035,  0.65531674],
       [ 0.22788542,  0.53109969, -0.37423035,  1.        , -0.06437078],
       [ 0.07305188,  0.58095927,  0.65531674, -0.06437078,  1.        ]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [422]:
display(np.round(x, 8))
display(np.round(pred_x, 8))

array([[-6.92344504,  0.65836955,  1.76877211,  4.12746274,  0.36884064],
       [-0.84061739, -1.4199143 ,  0.77624666,  7.23277999, -5.74849496],
       [-2.86609056, -2.35962907,  6.38027401, -1.0623987 , -0.09215568],
       [-0.67067865,  3.93362554, -1.22567741,  1.87910269, -3.91637218],
       [ 0.97438425, -3.64396441,  5.1482506 ,  1.48731282, -3.96598326]])

array([[-6.92344504,  0.65836955,  1.76877211,  4.12746274,  0.36884064],
       [-3.42712454,  0.32589476,  0.87554711,  2.04310553,  0.18257714],
       [-2.53634433,  0.241188  ,  0.64797439,  1.51206034,  0.13512158],
       [-1.14704837,  0.109076  ,  0.29304301,  0.68382133,  0.06110802],
       [-0.4675168 ,  0.04445747,  0.11943919,  0.27871358,  0.02490656]])

### PCA

In [423]:
arr = [x]
EV1 = []

for target_x in arr:
    n = len(target_x[0])

    x_t = np.transpose(target_x)
    y = x_t / np.sqrt(n)

    U, S, Vh = np.linalg.svd(y, full_matrices=True)
    eigenvalues = S * S
    sum_eigenvalues = np.sum(eigenvalues)
    explained_variances = eigenvalues / sum_eigenvalues
    # display(eigenvalues)
    # display(explained_variances)
    # display(np.sum(explained_variances))

    cov_x = np.matmul(np.transpose(y), y)
    V_Cx = np.matmul(Vh, cov_x)
    
    # print(np.matmul(V_Cx, np.transpose(Vh)))
    # print(f'{np.matmul(V_Cx[0], Vh[1]):.20f}\n')
    # print(f'{np.matmul(Vh[0], Vh[0]):.20f}\n')

    ## Confirm that XV = US
    # display(np.matmul(y, np.transpose(Vh))) 
    # display(np.matmul(U, np.diag(S)))

    ## Confirm that the mean of project vector y equals to zero.
    # project_y = np.matmul(Vh[0], target_x)
    # display(project_y)
    # display(np.mean(project_y))
    
    ## EV1
    EV1 = (Vh[0])
    # display(Vh[0])
    # print(Vh)
    

    # display(np.round(cov_x, 6))
    # print(np.dot(Vh[-1], cov_x[0]))
    # print(np.dot(Vh[-1], cov_x[1]))
    # print(np.dot(Vh[-1], cov_x[2]))
    # print(np.dot(Vh[-1], cov_x[3]))
    # print(np.dot(Vh[-1], cov_x[4]))

    cov_x_GaussForm = []
    add_col = []
    for i in range(len(cov_x[0])):
        add_col.append([np.dot(Vh[-1], cov_x[i])])

    add_col = np.array(add_col)

    cov_x_GaussForm = np.concatenate((cov_x, add_col), axis=1)
    cov_x_rref = sympy.Matrix(cov_x_GaussForm).rref()
    Base_Vec = []
    
    for i in cov_x_rref[0]:
        if i != 0 and i != 1:
            Base_Vec.append(i)
    
    print(Vh[-1] / Base_Vec)
    print(Base_Vec)
    print(Vh[-1])
    print('\n')
    print(cov_x)

    # print(np.dot(EV1, Base_Vec))

    # display(corr_x > 0)
    # display(Vh > 0)
    # display(V_Cx > 0)
    # display((Vh > 0) == (V_Cx > 0))


[0.996658432172425 0.996658432172425 0.996658432172425 0.996658432172422
 0.996658432172425]
[-0.362774764002706, 0.426087200060045, 0.547152645347740, -0.0378159653018875, -0.626701593871859]
[-0.36156253  0.4246634   0.5453243  -0.0376896  -0.62460743]


[[13.73361772  6.79817895  5.0311923   2.27533023  0.9273847 ]
 [ 6.79817895 17.73673074  0.71161669  6.0262654   8.38143725]
 [ 5.0311923   0.71161669 11.12548091 -3.36305389  7.48766981]
 [ 2.27533023  6.0262654  -3.36305389  7.25890056 -0.59410093]
 [ 0.9273847   8.38143725  7.48766981 -0.59410093 11.73470162]]


In [424]:
# import sympy
## row echelon form
# sympy.Matrix([[1, 0, 2, 4, -8],[0, 1, -3, -1, 6], [-3, -1, -3, 1, -6], [-1, 1, -5, -2, 8]]).rref()

#### New idea: Predict EV1 matrix

In [425]:
# EV1_Vote_Matrix = corr_x > 0
# EV1_Pred_Result = []

# EV1_Vote_Matrix = np.dstack((x, EV1_Vote_Matrix))

# for row in EV1_Vote_Matrix:
#     # display(row)
#     pos_abs_sum = 0
#     neg_abs_sum = 0

#     for entry in row:
#         if entry[1]:
#             pos_abs_sum += abs(entry[0])
#         else:
#             neg_abs_sum += abs(entry[0])

#     if pos_abs_sum >= neg_abs_sum:
#         EV1_Pred_Result.append(True)
#     else:
#         EV1_Pred_Result.append(False)

#     pos_abs_sum = 0
#     neg_abs_sum = 0


# # display(list(corr_x[0] > 0))
# display(list(EV1 > 0))
# display(EV1_Pred_Result)

In [426]:
# display()

y = a * x1 + Error.<br>
a * x1 can be either positive or negative.

In [427]:
# error_x = x - pred_x
# display(x)
# display(pred_x)
# display(error_x)
# display(corr_x)

In [428]:
# pred_EV1 = []
# n = len(pred_x[0])
# counter = 0

# for i in range(n):
#     for j in range(n):
#         Leader = pred_x[i][j] if abs(pred_x[i][j]) > abs(error_x[i][j]) else error_x[i][j]
#         if Leader > 0:
#             counter += 1
    
#     print(counter)
#     if counter > n/2:
#         pred_EV1.append(True)
#     else:
#         pred_EV1.append(False)
        
#     counter = 0

# display(pred_EV1)